"""add email confirmation code and expiry

Revision ID: 79cde303a420
Revises: 6102f5d4ee1a
Create Date: 2025-11-20 11:31:30.506899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79cde303a420'
down_revision: Union[str, Sequence[str], None] = '6102f5d4ee1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_confirmation_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('email_confirmation_expiry', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_confirmation_expiry')
    op.drop_column('users', 'email_confirmation_code')
    # ### end Alembic commands ###
